config/routes.rb
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  devise_for :admins, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # Mount the action cable
  mount ActionCable.server => '/cable'

  # API
  namespace :api do
    namespace :v1 do
      post  '/auth/signup', to: 'auth#signup'
      post  '/auth/login', to: 'auth#login'
      get   '/auth/check', to: 'auth#check'
      get   '/auth/me', to: 'auth#me'
      patch '/auth/me', to: 'auth#update'
      post  '/auth/upgrade', to: 'auth#upgrade'

      # TODO find a better routing for these
      # get  '/users/:id/posts', to: 'posts#for_user'
      get  '/users/professionals', to: 'users#index_professionals'
      post '/users/:id/reset', to: 'users#reset'

      resources :users, only: [ :show, :destroy, :update ] do
        collection do
          get 'suggestions'
          get 'professionals_suggestions'
          post 'search_professionals'
          post 'search'
        end

        member do
          get 'groups'
          get 'service_requests'
          get 'posts'
          get 'liked_posts'
          get 'activity_streak'
          get 'activities'
          get 'attended_activities'
        end

        get    'following', to: 'follows#index_following'
        get    'followers', to: 'follows#index_followers'
        get    'friends', to: 'follows#index_friends'

        post   'followers', to: 'follows#create'
        delete 'followers', to: 'follows#destroy'

        get    'reviews', to: 'reviews#index'
        post   'reviews', to: 'reviews#create'
      end

      resources :professionals, only: [ :index, :show ] do
        collection do 
          post 'signup'
          post 'filter'
        end
        member do
          get 'service_requests'
          get 'receipts'
        end
      end

      resources :service_requests, only: [ :show, :create ] do
        member do 
          post 'accept'
          post 'reject'
          post 'complete'
          post 'cancel'
          post 'approve'
        end
      end

      post '/posts/filter', to: 'posts#filter'

      resources :posts, only: [ :index, :show, :create, :destroy ] do
        collection do
          get 'category_top_posts'
          get 'category_posts'
          post 'rewatch'
          get 'taggable_users'
          post 'search_taggable_user'
          get 'categories'
        end
        resources :views, only: [ :index, :create ]
        resources :likes, only: [ :index, :create ]
        resources :reports, only: [ :index, :create ]
        resources :comments, only: [ :index, :create, :destroy ]
      end

      post '/activities/filter', to: 'activities#filter'

      resources :activities, only: [ :index, :show, :create, :update, :destroy ] do
        collection do
          get 'suggestions'
          post 'search'
        end
        resources :reports, only: [ :index, :create ]
        resources :participants, only: [ :index, :create ] do
          collection do
            get 'attendees'
          end
        end
      end

      post '/groups/filter', to: 'groups#filter'

      resources :groups do
        collection do
          get 'suggestions'
          post 'search'
        end
        member do 
          post 'leave'
        end
        resources :admins, only: [ :index, :create ] do
          collection do 
            post 'remove'
          end
        end
        resources :members, only: [ :index, :create ]
        resources :invites, only: [ :create ] do
          collection do 
            post 'invite_multiple'
          end
        end
        resources :requests, only: [ :index, :create ] do 
          collection do 
            post 'reject'
          end
          member do
            post 'accept'
          end
        end
        resources :reports, only: [ :index, :create ]
        resources :topics, only: [ :index, :create, :destroy ]
      end

      resources :topics, only: [:show, :destroy] do
        resources :likes, only: [ :index, :create, :destroy ]
        resources :comments, only: [ :index, :create, :destroy ]
        resources :reports, only: [ :index, :create ]
      end

      resources :comments, only: [ :index, :create, :destroy ] do
        resources :reports, only: [ :index, :create ]
      end

      resources :notifications, only: [ :index ] do
        collection do
          post 'delete'
          post 'mute'
          post 'unmute'
          post 'settings'
          get 'get_settings'
        end
      end

      resources :activations, only: [ :new, :edit ]

      delete '/posts/:post_id/likes', to: 'likes#destroy'
      delete '/topics/:topic_id/likes', to: 'likes#destroy'

      post  '/conversations/:conversation_id/messages/filter', to: 'messages#filter'

      resources :activity_streaks, only: [:create]

      resources :conversations, only: [:index, :create, :destroy] do
        resources :messages, only: [:index, :create] do 
          collection do
            post :destroy_messages
          end
        end
      end
    end
  end

  # Website
  # Password reset routing
  resources :password_resets, only: [:new, :create, :edit, :update]
  # Account activation routing
  resources :activations, only: [:new, :edit]
  # Contact routing
  post 'contact', to: 'contact#create'
  # Static pages
  get 'help', to: 'contact#new'
  get 'privacy', to: 'static#privacy'
  get 'terms', to: 'static#terms'
  # Root controller
  root 'static#home'
end

app/views/layouts/_email_form.html.erb
  <div class="form-group">
    <%= text_field_tag :email, nil, class: 'form-control', required: '', placeholder: 'Email' %>
  </div>
  <div class="form-group">
    <p hidden="Thank you for your interest, a WeFit representative will be in touch shortly?"><p>
  </div>
  
  <div class="form-group">
    <%= submit_tag "Register",:onclick => ('Thank you for your interest, a WeFit representative will be in touch shortly?'), class: 'btn btn-green btn-md w-25' %>
  </div> 

app/views/layouts/_mobile_page.html.erb
<div class="mobile-logo">
  <%= image_tag 'logo-transparent.svg', size: '100x100', alt: 'logo' %>
</div>
<div class="centered">
  <h1>Coming Soon</h1>
  <lottie-player
    src="https://assets3.lottiefiles.com/datafiles/a7kd2uysziSJpYt/data.json" background="transparent" speed="0.5" style="width: 275px; height: 275px; margin: 1vh auto 1vh auto;" loop autoplay >
  </lottie-player>
  <h3>The healthy social network</h3>
</div>
<div id="bottom">
  <div class="bottom-logo">
    <%= image_tag "text-transparent-white-new.svg", alt: "Text Logo", size: '90x28' %>
  </div>
  <p>WeFit Inc &copy; <%= Time.current.year %></p>
</div>
<script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="<%= I18n.locale %>" data-wf-page="5fa4b478c886f99c7b1bd547" data-wf-site="5fa4b478304dc7e402fa47a8">
<head>
  <%# Device meta stuff %>
  <meta charset="utf-8">
  <meta content="Webflow" name="generator">
  <meta name="theme-color" content="#ff0800">
  <meta name="msapplication-TileColor" content="#ff0800">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <%# Rails authenticity stuff %>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%# SEO Stuff %>
  <title>WeFit - <%= if content_for?(:title) then yield(:title) else 'The Healthy Social Network' end %></title>
  <meta content="WeFit is a one-of-a-kind community with features that help keep you motivated, supported, and connected throughout your health journey." name="description">
  <meta content="WeFit - The Healthy Social Network" property="og:title">
  <meta content="WeFit is a one-of-a-kind community with features that help keep you motivated, supported, and connected throughout your health journey." property="og:description">
  <meta content="WeFit - The Healthy Social Network" property="twitter:title">
  <meta content="WeFit is a one-of-a-kind community with features that help keep you motivated, supported, and connected throughout your health journey." property="twitter:description">
  <meta property="og:type" content="website">
  <meta content="summary_large_image" name="twitter:card">

  <!-- App CSS -->
  <%= stylesheet_link_tag 'application' %>
  
  <!-- App JS -->
  <script src="https://ajax.googleapis.com/ajax/libs/webfont/1.6.26/webfont.js" type="text/javascript"></script>
  <script type="text/javascript">WebFont.load({google: {families: ["Nunito Sans:regular,600,700,800"]}});</script>
  <!-- [if lt IE 9]><script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js" type="text/javascript"></script><![endif] -->
  <script type="text/javascript">!function(o,c){var n=c.documentElement,t=" w-mod-";n.className+=t+"js",("ontouchstart"in o||o.DocumentTouch&&c instanceof DocumentTouch)&&(n.className+=t+"touch")}(window,document);</script>

  <%# Favicon %>
  <%= favicon_link_tag 'favicon.svg' %>
  <%= favicon_link_tag 'favicon.svg', rel: 'apple-touch-icon' %>
</head>
<body>
  <!-- Main content -->
  <%= yield %>
  <!-- Footer -->
  <footer id="footer" class="footer">
    <div class="footer-row">
      <div class="container flex">
        <%= link_to (image_tag 'logo-transperant-1.svg', class: 'footer-logo'), root_path, class: 'footer-logo-link-block w-inline-block w--current' %>
        <div class="copyright-block right flex-horizontal">
          <%= link_to (image_tag 'App-Store.svg', class: "app-store-btn"), "https://www.apple.com/ios/app-store/", target: "_blank", class: "app-link-block w-inline-block" %>
        </div>
      </div>
    </div>
    <div class="footer-row bottom">
      <div class="container flex">
        <div class="copyright-block">
          <div class="copyright-text">&copy; WeFit Inc. - <%= Time.zone.now.year %></div>
        </div>
        <div class="copyright-block right">
          <%= link_to "Terms", terms_path, class:"copyright-text right" %>
          <%= link_to "Privacy", privacy_path, class:"copyright-text right" %>
          <%= link_to "Help Center", help_path, class:"copyright-text right last" %>
        </div>
      </div>
    </div>
  </footer>
  <script src="https://d3e54v103j8qbb.cloudfront.net/js/jquery-3.5.1.min.dc5e7f18c8.js?site=5fa4b478304dc7e402fa47a8" type="text/javascript" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
  <%= javascript_include_tag 'application' %>
  <!-- [if lte IE 9]><script src="https://cdnjs.cloudflare.com/ajax/libs/placeholders/3.0.2/placeholders.min.js"></script><![endif] -->
</body>
</html>